language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed quyetnn1102/udagram-api-feed:v3
  - docker tag udagram-api-user quyetnn1102/udagram-api-user:v3
  - docker tag udagram-frontend quyetnn1102/udagram-frontend:v3
  - docker tag reverseproxy quyetnn1102/reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push quyetnn1102/udagram-api-feed:v3
  - docker push quyetnn1102/udagram-api-user:v3
  - docker push quyetnn1102/udagram-frontend:v3
  - docker push quyetnn1102/reverseproxy:v3