apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagram-cluster
  region: us-west-2
  version: "1.22"

managedNodeGroups:
  - name: udagram-cluster-ng
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1    
    maxSize: 4
    ssh:
      allow: true
      publicKeyPath: /Users/quyetnn/Projects/Udacity/Cloud Developer/project3-udagram-microservices/udagram-deployment/eks/ec2-keypair.pub
      
cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
