apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-user  
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: quyetnn1102/udagram-api-user
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1536Mi"
            cpu: "500m"       
        env:
        - name: ACCESS_CONTROL_ALLOW_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: ACCESS_CONTROL_ALLOW_ORIGIN 
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_USERNAME
      restartPolicy: Always


