version: "3.8"
services:
  reverseproxy:
    build:
      context: ../../udagram-reverseproxy
    image: quyetnn1102/udagram-reverseproxy
  backend_user:
    build:
      context: ../../udagram-api-user
    image: quyetnn1102/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed  
    image: quyetnn1102/udagram-api-feed  
  frontend:
    build:
      context: ../../udagram-frontend  
    image: quyetnn1102/udagram-frontend
